name: ICTD Lab
url: http://ictd.cs.washington.edu

exclude: [bibble, README.md, Makefile]

# use this library to parse Markdown
#markdown: redcarpet
#redcarpet:
#    extensions: [smart, tables, with_toc_data, strikethrough]

# colorize code snippets with the pygment module
highlighter: rouge

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Sections on the "people" page.
roles:
    - {key: faculty, name: Faculty, display: full}
    - {key: postdoc, name: Researchers, display: full}
    - {key: grad, name: Graduate Students, display: short}
    - {key: ugrad, name: Undergraduate Students}
    #- {key: collab, name: Collaborators}
    - {key: alum, name: Alumni, display: short}
    # - {key: staff, name: Staff, display: short}
    - {key: memory, name: "In Memory", display: full}

# Number of news stories on the front page.
front_page_news: 8

# Base pathname for links.
base: ''

# Navigation bar links.
navigation:
    - title: Home
      link: /
    - title: People
      link: /people.html
    - title: Blog
      link: https://medium.com/uw-ictd
    - title: Research
      link: /research/
    - title: Publications
      link: /publications.html
    - title: Seminars
      link: /seminars.html

nav_dfs:
    - title: Home
      link: /dfs/
    - title: Open Session
      link: /dfs/ictd_open_session.html
    - title: DFS Background
      link: /dfs/background_documents.html

# Rewriting of old path names.
wiki_redirects:
    People: people.html
    Projects: research/
    Publications: publications.html
    Seminars: seminars.html
    Funding: ''
    Main_Page: ''

